### ISSUE TITLE
Class 'iContact\Exception' Not Found

### ISSUE THREAD

**Issue by kojoduncan** [mizanur-rahman/icontact-php-api#1]
Getting this error lately. My code is below. What am I doing wrong?

```
<?php

// Load the iContact library
require '../../lib/config.php';
require RESOURCE_DIR.'/vendor/autoload.php';
use iContact\iContactApi;

// Give the API your information
iContactApi::getInstance()->setConfig(array(
'appId'       => IC_APP_ID,
'apiUsername' => 'redacted',
'apiPassword' => 'redacted'
)); 

$oiContact = iContactApi::getInstance();
try {
$success = $oiContact->setAccountId();
} catch (Exception $oException) { 
// Catch any exceptions
// Dump errors
$error = $oiContact->getErrors();
// Grab the last raw response data
$data = $oiContact->getLastResponse();
$error_description = json_decode($data);
// Grab the last raw request data
// var_dump($oiContact->getLastRequest());
}
```

**Comment by mizan3008** [comment]
sorry for late response, you can try this `catch (\Exception $oException)`

**Comment by kojoduncan** [comment]
Hello,

Thanks for the reply. I tried it and I'm still getting the same error. Here is the full error details:
`
[23-Oct-2016 19:09:53 America/Detroit] PHP Fatal error:  Uncaught Error: Class 'iContact\Exception' not found in /home/swiftaud/public_html/clients/lib/vendor/mizanur/icontact-api-php/src/iContact/iContactApi.php:463
Stack trace:
#0 /home/swiftaud/public_html/clients/lib/vendor/mizanur/icontact-api-php/src/iContact/iContactApi.php(1019): iContact\iContactApi->makeCall('/a/', 'get', NULL, 'accounts')
#1 /home/swiftaud/public_html/clients/lib/vendor/mizanur/icontact-api-php/src/iContact/iContactApi.php(888): iContact\iContactApi->setAccountId()
#2 /home/swiftaud/public_html/clients/login/icontact/ic_lists.php(62): iContact\iContactApi->getLists()
#3 {main}
  thrown in /home/swiftaud/public_html/clients/lib/vendor/mizanur/icontact-api-php/src/iContact/iContactApi.php on line 463
`

**Comment by kojoduncan** [comment]
Found the problem please change line 463 of your iContactAPi.php file to:

```
// Check for set errors
if (!empty($this->aErrors)) {
// Throw a new exception
throw new \Exception('Errors have occurred and the system cannot continue.  Use getErrors() for details.');
}
```

**Comment by mizan3008** [comment]
@kojoduncan 
feel free to commit and make Pull request, I will review and merge.

Thanks

**Comment by mizan3008** [comment]
@kojoduncan I have applied a fix, please take a look now once you free.

Thanks
